name: Test & Lint Todo App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        working-directory: ./todo-app
        run: npm ci
      - name: Run linter
        working-directory: ./todo-app
        run: npm run lint
      - name: Run tests
        working-directory: ./todo-app
        run: npm test