name: Build and Deploy to Render

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # السماح بتشغيل يدوي

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Prepare site directory
      run: |
        # إنشاء مجلد _site إذا لم يكن موجودًا
        mkdir -p _site

    - name: Copy docs to _site
      run: |
        # استنساخ المستوديع (تم في الخطوة السابقة)
        echo "Repository already checked out in previous step"

        # نسخ محتويات مجلد docs إلى مجلد _site إذا كان موجودًا
        if [ -d "docs" ]; then
          echo "Copying docs to _site..."
          cp docs/* _site/ 2>/dev/null || echo "No files found in docs directory"
        else
          echo "No docs directory found"
        fi

    - name: Create index.html if missing
      run: |
        # إنشاء ملف index.html إذا لم يكن موجودًا في مجلد _site
        if [ ! -f _site/index.html ]; then
          echo "Creating index.html..."
          cat > _site/index.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Stampcoin Platform</title>
<style type="text/css">
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
line-height: 1.6;
}
</style>
</head>
<body>
<h1>Welcome to the Stampcoin Platform</h1>
</body>
</html>
EOF
        else
          echo "index.html already exists"
        fi

    - name: Build Docker image
      run: |
        docker build -t stampcoin-platform .

    - name: Deploy to Render
      uses: appleboy/render-action@master
      with:
        service_id: ${{ secrets.RENDER_SERVICE_ID }}
        api_key: ${{ secrets.RENDER_API_KEY }}
        service_name: stampcoin-platform
        service_type: web
        env_vars: |
          NODE_ENV=production
          PORT=8080
          HOST=0.0.0.0
          RENDER_OUTBOUND_IPS="74.220.48.0/24 74.220.56.0/24"
        dockerfilePath: ./Dockerfile
        docker_context: .
        dockerfile: Dockerfile
        docker_build_command: docker build -t stampcoin-platform .
        service_region: oregon
        service_instance_type: starter
        service_health_check_path: /
        service_health_check_timeout: 60s
        logs_url: https://api.render.com/services/$SERVICE_ID/logs
        on_failure: always
